name: Tests
on: [pull_request]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://www.ck12.org/schools/california/
          EXTERNAL: false
          TLD: true
          LIST: true
          UPGRADE: true
